# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoldmanSachsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoldmanSachsDemo
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.3'

  target 'GoldmanSachsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoldmanSachsDemoUITests' do
    # Pods for testing
  end

end
